# Generated by Django 5.2.7 on 2025-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('director', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('duration', models.IntegerField(verbose_name='Продолжительность (мин)')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cast', models.TextField(verbose_name='Актерский состав')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на постер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
